config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"


  resources :projects do
    post 'add_comment', on: :member
    post 'change_status', on: :member
  end

  # root 'projects#show'
  root to: 'projects#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :project

  validates :content, presence: true


  
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :comments, dependent: :destroy

	# Enum for status
  	enum status: [:active, :inactive]


  	# Method to add a comment to the project
  	def add_comment(content)
    	comment = comments.create(content: content)

    	print(comment.errors.inspect)
  	end

  	def delete_comment()
    	comment.destroy
  	end

  	# Method to change the status of the project and track it
  	def change_status(new_status)
    	self.status = new_status.downcase.to_sym
    	save
    end

    def status_active?
   		status.to_sym == :active
   	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :add_comment, :change_status]

  
  def index
  	@projects = Project.order(created_at: :desc)
  end	

  def show
    @comments = @project.comments.order(created_at: :desc)
  end

  def new
  	@project = Project.new
  end	

  def edit
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy

    puts project.inspect

    respond_to do |format|
      format.html { redirect_to @project, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  # Action to add a comment
  def add_comment
    comment = params[:content]
    @project.add_comment(comment)
    redirect_to @project
  end

  def delete_comment
    @project.delete_comment(comment)
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Action to change the status
  def change_status
    status = params[:status]
    @project.change_status(status)
    redirect_to @project
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
      params.require(:project).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectConversationHistoryApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', placeholder: "Write a project name...", value: project.name %>
  </div>

  <%= form.submit "Save", class: 'btn btn-primary' %>
<% end %>

app/views/projects/edit.html.erb
<div class="card my-5">
  <div class="card-body">
    <h1>Edit Project Details</h1>

    <%= render 'form', project: @project %>

    <div class="mt-2">
      <%= link_to 'Back', projects_path, class: 'btn btn-light' %>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h2>List of Projects: </h2>
<hr>
<% @projects.each do |project| %>
  <div class="card">
    <div class="card-body">
      <h3 class="card-title"><%= project.name %></h3>
      <%= link_to 'Show', project_path(project), class: 'btn btn-info mr-2' %>
      <%= link_to 'Edit', edit_project_path(project), class: 'card-link' %>
    </div>
  </div>
  <% end %>
  <hr>
  <%= link_to 'Create New Project', new_project_path, class: 'btn btn-primary' %>

app/views/projects/new.html.erb
<div class="card my-5">
  <div class="card-body">
    <h1>New Project</h1>

    <%= render 'form', project: @project %>

    <%= link_to 'Back', projects_path, class: 'btn btn-light mt-2' %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="card my-5">
  <div class="card-body">
    <p id="notice"><%= notice %></p>

    <h2 class="text-center">Project: <%= @project.name %></h2>
    <div class="my-4">
      <p>Status: <%= @project.status %></p>
    </div>
    <hr>
    <h3>Change status:</h3>
      <%= form_with url: change_status_project_path(@project), method: :post, local: true do |f| %>
      <%= f.select :status, options_for_select(['Active', 'Inactive']) %>
      <%= f.submit "Change" %>
    <% end %>
  </div>
</div>

<div class="card my-1">
  <div class="card-body">
    <p class="font-weight-bold">Comments: </p>
    <%= form_with url: add_comment_project_path(@project), method: :post, local: true do |f| %>
      <div class="form-group">
        <%= f.text_area :content, class: 'form-control', placeholder: "Add a comment..." %>
        <%= f.submit 'Submit', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

<h3>Comments Section:</h3>
<ul>
  <% @comments.each do |entry| %>
    <li>
      <%= entry.content %>
      <br>
      <small><%= entry.created_at.strftime("%b %d, %Y %H:%M") %></small>
    </li>
  <% end %>
</ul>
<%= link_to 'Delete', projects_path, method: :delete, class: 'btn btn-danger mr-2' %>
<%= link_to 'Back', projects_path, class: 'btn btn-light' %>